/* Generated By:JavaCC: Do not edit this line. SimpleCConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPARENT = 9;
  /** RegularExpression Id. */
  int RPARENT = 10;
  /** RegularExpression Id. */
  int VOID = 11;
  /** RegularExpression Id. */
  int CHARSS = 12;
  /** RegularExpression Id. */
  int CHARS = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int LONG = 15;
  /** RegularExpression Id. */
  int LONGS = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int CONTINUE = 23;
  /** RegularExpression Id. */
  int BREAK = 24;
  /** RegularExpression Id. */
  int RETURN = 25;
  /** RegularExpression Id. */
  int DOUBLES = 26;
  /** RegularExpression Id. */
  int DOUBLE = 27;
  /** RegularExpression Id. */
  int LCURLY = 28;
  /** RegularExpression Id. */
  int RCURLY = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int LBRAC = 31;
  /** RegularExpression Id. */
  int RBRAC = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int EQUALEQUAL = 34;
  /** RegularExpression Id. */
  int EQUAL = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int ANDAND = 38;
  /** RegularExpression Id. */
  int NOTEQUAL = 39;
  /** RegularExpression Id. */
  int LESS = 40;
  /** RegularExpression Id. */
  int GREATER = 41;
  /** RegularExpression Id. */
  int LESSEQUAL = 42;
  /** RegularExpression Id. */
  int GREATEQUAL = 43;
  /** RegularExpression Id. */
  int PLUS = 44;
  /** RegularExpression Id. */
  int MINUS = 45;
  /** RegularExpression Id. */
  int MULTIPLE = 46;
  /** RegularExpression Id. */
  int DIVIDE = 47;
  /** RegularExpression Id. */
  int MOD = 48;
  /** RegularExpression Id. */
  int ID = 49;
  /** RegularExpression Id. */
  int CHAR_CONST = 50;
  /** RegularExpression Id. */
  int STRING_CONST = 51;
  /** RegularExpression Id. */
  int DOUBLE_CONST = 52;
  /** RegularExpression Id. */
  int INTEGER_CONST = 53;
  /** RegularExpression Id. */
  int PRINTING_CHAR = 54;
  /** RegularExpression Id. */
  int DIGIT = 55;
  /** RegularExpression Id. */
  int OCTAL = 56;
  /** RegularExpression Id. */
  int HEX_DIGIT = 57;
  /** RegularExpression Id. */
  int LETTER = 58;
  /** RegularExpression Id. */
  int OTHER_CHAR = 59;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"(\"",
    "\")\"",
    "\"void\"",
    "\"char**\"",
    "\"char*\"",
    "\"char\"",
    "\"long\"",
    "\"long*\"",
    "\"int\"",
    "\"else\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"continue\"",
    "\"break\"",
    "\"return\"",
    "\"double*\"",
    "\"double\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"==\"",
    "\"=\"",
    "\"&\"",
    "\"||\"",
    "\"&&\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<ID>",
    "<CHAR_CONST>",
    "<STRING_CONST>",
    "<DOUBLE_CONST>",
    "<INTEGER_CONST>",
    "<PRINTING_CHAR>",
    "<DIGIT>",
    "<OCTAL>",
    "<HEX_DIGIT>",
    "<LETTER>",
    "<OTHER_CHAR>",
  };

}
